const ADD_COMPANY = 'ADD_COMPANY'
const ADD_CRITERIA = 'ADD_CRITERIA'
const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST'
const ADD_CRITERIA_DIMENSIONS = 'ADD_CRITERIA_DIMENSIONS'
const ADD_ALL_COMPANIES = 'ADD_ALL_COMPANIES'
const RESET_COMPANIES = 'RESET_COMPANIES'

export default {
    ADD_COMPANY,
    ADD_CRITERIA,
    ADD_DATA_REQUEST,
    ADD_CRITERIA_DIMENSIONS,
    ADD_ALL_COMPANIES,
    RESET_COMPANIES,
}