const ADD_COMPANY = 'ADD_COMPANY'
const ADD_ALL_COMPANIES = 'ADD_ALL_COMPANIES'
const RESET_COMPANIES = 'RESET_COMPANIES'

export default {
    ADD_COMPANY,
    ADD_ALL_COMPANIES,
    RESET_COMPANIES,
}