const FETCH_CUSTOMER_DATA = 'FETCH_CUSTOMER_DATA'
const DROP_CUSTOMER_BASE = 'DROP_CUSTOMER_BASE'
const DROP_CUSTOMER_VEHICLE = 'DROP_CUSTOMER_VEHICLE'
const EDIT_CUSTOMER_BASE = 'EDIT_CUSTOMER_BASE'
const EDIT_CUSTOMER_VEHICLE = 'EDIT_CUSTOMER_VEHICLE'
const INFO_CUSTOMER_BASE = 'INFO_CUSTOMER_BASE'
const INFO_CUSTOMER_VEHICLE = 'INFO_CUSTOMER_VEHICLE'


export default {
    FETCH_CUSTOMER_DATA,
    DROP_CUSTOMER_BASE,
    DROP_CUSTOMER_VEHICLE,
    EDIT_CUSTOMER_BASE,
    EDIT_CUSTOMER_VEHICLE,
    INFO_CUSTOMER_BASE,
    INFO_CUSTOMER_VEHICLE
}